spring:
  profiles:
    active: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    #    locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
#    default-schema: rentcar
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
    schemas: rentcar
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/rentcar"
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/rentcar"

server:
  port: 8081
jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 600000

---

spring:
  profiles: jwt-top-secret
jwt:
  secret: 111*%--+devsecret777**

---

spring:
  profiles:
    active: dev
    include: jwt-top-secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    #    locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    #    default-schema: rentcar
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
    schemas: rentcar
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/rentcar"
      maximum-pool-size: 5
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/rentcar"

server:
  port: 8081
jwt:
  secret: devsecret777**
  expiration: 100000